
spring:
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://13.124.68.252:3306/barogo?characterEncoding=UTF-8
    username: barogo
    password: Team400!
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 659754322905-qglt5anks2qqcdkn1e22jo46fn01f8ig.apps.googleusercontent.com
            client-secret: ENC(9OIQDUegz5eyb2bE5QjYlXr8qDGGvQ7LNJYUi6yfXrJV1mRtQrLNS13cdW256z2n)
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email
          github:
            client-id: 80e1918acbeeb486e392
            client-secret: ENC(XAiNcKYyRL6ty+LufVNEeO99V0RRs7l+EgTjwHnX52tIithZQErxEGERty7ol93HSrcbMW1WDaY=)
            scope: profile,email
          naver:
            client-id: QX2BY7T7WQRSQwBIXrGV
            client-secret: ENC(3g+2XVASZnt7lw3Uwk8pL2871kbKUO1G)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name-attribute: response

my:
  kakao_map_key: e09d681977d1f378b28b043a06aba912
